resolver: lts-8.23

packages:
- '.'
- location:
    git: git@github.com:haskell-works/hw-hedgehog.git
    commit: 0fd750bbbf733045027e1bc4a61f2b0df63591c7
  extra-dep: true

extra-deps:
  - hedgehog-0.5

flags: {}

extra-package-dbs: []
